version : "3.8"
services:

    communication-module:
        build: ./communicationModule/
        ports: 
            - 8001:7001
        restart: always

    rating-module:
        build: ./ratingModule/
        restart: always
        depends_on: 
            - mymongodb

    rideshare-backend:
        build: ./RideShare-Backend/
        restart: always
        depends_on: 
            - communication-module
    nginx:
        build: ./nginx/
        ports: 
            - 9000:80
        depends_on: 
            - rating-module
            - rideshare-backend
    mymongodb:
        image: mongo
        ports: 
            - 2700:27017
        volumes:
            - mongodb_data_container:/data/db   

volumes:
    mongodb_data_container:

