version : "3.8"

networks:
    redNet:
      ipam:
        config:
          - subnet: 10.100.0.0/24

services:

    rating-module:
        build: ./ratingModule/
        restart: always
        depends_on: 
            - mymongodb
        networks:
            redNet:
                ipv4_address: 10.100.0.5 

    communication-module-dhaka:
        build: ./communicationModule/
        restart: always
        networks:
            redNet:
                ipv4_address: 10.100.0.3 

    rideshare-backend-dhaka:
        build: ./RideShare-Backend/
        restart: always
        depends_on: 
            - communication-module-dhaka
        environment: 
            - SERVERLOCATION=dhaka
        # networks:
        #     redNet:
        #         ipv4_address: 10.100.0.11

    nginx-dhaka:
        build: ./nginx/
        depends_on: 
            - rating-module
            - rideshare-backend-dhaka
        environment: 
            - RIDE_SERVER=rideshare-backend-dhaka
            - RATING=rating-service
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            redNet:
                ipv4_address: 10.100.0.101

    communication-module-chittagong:
        build: ./communicationModule/
        restart: always
        networks:
            redNet:
                ipv4_address: 10.100.0.4

    rideshare-backend-chittagong:
        build: ./RideShare-Backend/
        restart: always
        depends_on: 
            - communication-module-chittagong
        environment: 
            - SERVERLOCATION=chittagong
        # networks:
        #     redNet:
        #         ipv4_address: 10.100.0.2

    nginx-chittagong:
        build: ./nginx/
        depends_on: 
            - rating-module
            - rideshare-backend-chittagong
        environment: 
            - RIDE_SERVER=rideshare-backend-chittagong
            - RATING=rating-service
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            redNet:
                ipv4_address: 10.100.0.102

    mymongodb:
        image: mongo
        ports: 
            - 2700:27017
        volumes:
            - mongodb_data_container:/data/db   
        networks:
            redNet:
                ipv4_address: 10.100.0.15

volumes:
    mongodb_data_container:

